homeassistant_latitude: 48.8687679
homeassistant_longitude: 2.346756
homeassistant_elevation: 0
homeassistant_external_url: http://localhost:8123
homeassistant_internal_url: http://localhost:8123
# homeassistant_trusted_proxy:

homeassistant_recorder_db_url: postgresql://homeassistant:password@localhost:5432/homeassistant
